import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  root: {
    padding: '32px 36px',
    fontFamily: "'DM Sans', sans-serif",
    maxWidth: 900,
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 24,
  },
  backBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 13,
    fontWeight: 500,
    color: '#64748B',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontFamily: "'DM Sans', sans-serif",
    padding: 0,
  },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
  },
  titleGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    flex: 1,
  },
  pageTitle: {
    fontSize: 22,
    fontWeight: 600,
    color: '#0F172A',
    letterSpacing: '-0.5px',
  },
  metaRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap' as const,
  },
  metaItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    fontSize: 13,
    color: '#64748B',
  },
  updateBtn: {
    height: 42,
    padding: '0 20px',
    borderRadius: 10,
    border: 'none',
    background: '#0F172A',
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: '1fr 300px',
    gap: 20,
    alignItems: 'start',
  },
  card: {
    background: '#FFFFFF',
    border: '1px solid #E2E8F0',
    borderRadius: 16,
    padding: '20px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  cardLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: '#94A3B8',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  descText: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 1.7,
    whiteSpace: 'pre-wrap' as const,
  },
  infoRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px 0',
    borderBottom: '1px solid #F8FAFC',
  },
  infoLabel: {
    fontSize: 12,
    color: '#94A3B8',
    fontWeight: 500,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  infoValue: {
    fontSize: 13,
    color: '#0F172A',
    fontWeight: 500,
  },
  votePill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 14px',
    borderRadius: 20,
    background: '#EEF2FF',
    color: '#6366F1',
    fontSize: 14,
    fontWeight: 600,
  },
  loadingWrap: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '50vh',
    color: '#94A3B8',
    fontSize: 14,
    fontFamily: "'DM Sans', sans-serif",
  },
  overlay: {
    position: 'fixed' as const,
    inset: 0,
    background: 'rgba(15,23,42,0.4)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    padding: 20,
  },
  modal: {
    background: '#FFFFFF',
    borderRadius: 16,
    padding: '28px',
    width: '100%',
    maxWidth: 420,
    boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: 600,
    color: '#0F172A',
  },
  modalSubtitle: {
    fontSize: 13,
    color: '#94A3B8',
    marginTop: -8,
  },
  label: {
    fontSize: 13,
    fontWeight: 500,
    color: '#374151',
  },
  select: {
    height: 42,
    padding: '0 12px',
    borderRadius: 10,
    border: '1.5px solid #E2E8F0',
    background: '#F8FAFC',
    fontSize: 13,
    color: '#0F172A',
    fontFamily: "'DM Sans', sans-serif",
    outline: 'none',
    width: '100%',
  },
  modalActions: {
    display: 'flex',
    gap: 10,
    justifyContent: 'flex-end',
  },
  cancelBtn: {
    height: 40,
    padding: '0 18px',
    borderRadius: 10,
    border: '1.5px solid #E2E8F0',
    background: '#FFFFFF',
    fontSize: 13,
    fontWeight: 500,
    color: '#374151',
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
  },
  confirmBtn: {
    height: 40,
    padding: '0 18px',
    borderRadius: 10,
    border: 'none',
    background: '#0F172A',
    fontSize: 13,
    fontWeight: 600,
    color: '#FFFFFF',
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
  },
}