import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  root: {
    padding: '32px 36px',
    fontFamily: "'DM Sans', sans-serif",
    maxWidth: 1200,
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 24,
  },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: 600,
    color: '#0F172A',
    letterSpacing: '-0.5px',
  },
  pageSubtitle: {
    fontSize: 13,
    color: '#94A3B8',
    marginTop: 4,
  },
  roleBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 14px',
    borderRadius: 20,
    fontSize: 12,
    fontWeight: 600,
  },
  tabs: {
    display: 'flex',
    gap: 4,
    background: '#F1F5F9',
    padding: 4,
    borderRadius: 12,
    width: 'fit-content',
  },
  tab: {
    height: 36,
    padding: '0 18px',
    borderRadius: 9,
    border: 'none',
    fontSize: 13,
    fontWeight: 500,
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
    transition: 'all 0.15s',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  tabActive: {
    background: '#FFFFFF',
    color: '#0F172A',
    boxShadow: '0 1px 4px rgba(0,0,0,0.08)',
  },
  tabInactive: {
    background: 'transparent',
    color: '#64748B',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: '#0F172A',
  },
  sectionSubtitle: {
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 2,
  },
  addBtn: {
    height: 38,
    padding: '0 16px',
    borderRadius: 10,
    border: 'none',
    background: '#0F172A',
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  tableCard: {
    background: '#FFFFFF',
    border: '1px solid #E2E8F0',
    borderRadius: 16,
    overflow: 'hidden',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
  },
  th: {
    fontSize: 11,
    fontWeight: 600,
    color: '#94A3B8',
    textAlign: 'left' as const,
    padding: '12px 16px',
    letterSpacing: '0.05em',
    textTransform: 'uppercase' as const,
    borderBottom: '1px solid #F1F5F9',
    background: '#FAFAFA',
  },
  td: {
    padding: '13px 16px',
    borderBottom: '1px solid #F8FAFC',
    verticalAlign: 'middle' as const,
    fontSize: 13,
    color: '#0F172A',
  },
  activePill: {
    fontSize: 11,
    fontWeight: 600,
    padding: '3px 10px',
    borderRadius: 20,
    display: 'inline-block',
  },
  iconBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    border: '1.5px solid #E2E8F0',
    background: '#FFFFFF',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.15s',
    marginLeft: 6,
  },
  readOnlyNote: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 14px',
    background: '#F0F9FF',
    borderRadius: 10,
    border: '1px solid #BAE6FD',
    fontSize: 13,
    color: '#0369A1',
    marginBottom: 16,
  },
  emptyState: {
    textAlign: 'center' as const,
    padding: '48px 0',
    color: '#94A3B8',
    fontSize: 13,
  },

  // Modal
  overlay: {
    position: 'fixed' as const,
    inset: 0,
    background: 'rgba(15,23,42,0.4)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    padding: 20,
  },
  modal: {
    background: '#FFFFFF',
    borderRadius: 16,
    padding: '28px',
    width: '100%',
    maxWidth: 460,
    boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: 600,
    color: '#0F172A',
  },
  fieldWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: 7,
  },
  label: {
    fontSize: 13,
    fontWeight: 500,
    color: '#374151',
  },
  input: {
    height: 42,
    padding: '0 12px',
    borderRadius: 10,
    border: '1.5px solid #E2E8F0',
    background: '#F8FAFC',
    fontSize: 13,
    color: '#0F172A',
    fontFamily: "'DM Sans', sans-serif",
    outline: 'none',
  },
  textarea: {
    padding: '10px 12px',
    borderRadius: 10,
    border: '1.5px solid #E2E8F0',
    background: '#F8FAFC',
    fontSize: 13,
    color: '#0F172A',
    fontFamily: "'DM Sans', sans-serif",
    outline: 'none',
    resize: 'vertical' as const,
    minHeight: 72,
  },
  select: {
    height: 42,
    padding: '0 12px',
    borderRadius: 10,
    border: '1.5px solid #E2E8F0',
    background: '#F8FAFC',
    fontSize: 13,
    color: '#0F172A',
    fontFamily: "'DM Sans', sans-serif",
    outline: 'none',
  },
  modalActions: {
    display: 'flex',
    gap: 10,
    justifyContent: 'flex-end',
    marginTop: 4,
  },
  cancelBtn: {
    height: 40,
    padding: '0 18px',
    borderRadius: 10,
    border: '1.5px solid #E2E8F0',
    background: '#FFFFFF',
    fontSize: 13,
    fontWeight: 500,
    color: '#374151',
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
  },
  confirmBtn: {
    height: 40,
    padding: '0 18px',
    borderRadius: 10,
    border: 'none',
    background: '#0F172A',
    fontSize: 13,
    fontWeight: 600,
    color: '#FFFFFF',
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
  },
}