import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  root: {
    padding: '32px 36px',
    fontFamily: "'DM Sans', sans-serif",
    maxWidth: 1400,
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 24,
  },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: 600,
    color: '#0F172A',
    letterSpacing: '-0.5px',
  },
  pageSubtitle: {
    fontSize: 13,
    color: '#94A3B8',
    marginTop: 4,
  },
  filtersRow: {
    display: 'flex',
    gap: 12,
    alignItems: 'center',
    flexWrap: 'wrap' as const,
  },
  select: {
    height: 40,
    padding: '0 12px',
    borderRadius: 10,
    border: '1.5px solid #E2E8F0',
    background: '#FFFFFF',
    fontSize: 13,
    color: '#0F172A',
    fontFamily: "'DM Sans', sans-serif",
    outline: 'none',
    cursor: 'pointer',
    minWidth: 160,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
    gap: 16,
  },
  ideaCard: {
    background: '#FFFFFF',
    border: '1px solid #E2E8F0',
    borderRadius: 14,
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    transition: 'transform 0.15s, box-shadow 0.15s',
    cursor: 'default',
  },
  ideaCardTop: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  ideaTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: '#0F172A',
    lineHeight: 1.4,
    flex: 1,
  },
  ideaDesc: {
    fontSize: 13,
    color: '#64748B',
    lineHeight: 1.6,
    display: '-webkit-box',
    WebkitLineClamp: 3,
    WebkitBoxOrient: 'vertical' as const,
    overflow: 'hidden',
  },
  ideaFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  votePill: {
    display: 'flex',
    alignItems: 'center',
    gap: 5,
    fontSize: 13,
    fontWeight: 600,
    color: '#6366F1',
    background: '#EEF2FF',
    padding: '4px 10px',
    borderRadius: 20,
  },
  dateText: {
    fontSize: 12,
    color: '#94A3B8',
  },
  actionBtn: {
    height: 32,
    padding: '0 14px',
    borderRadius: 8,
    border: '1.5px solid #E2E8F0',
    background: '#FFFFFF',
    fontSize: 12,
    fontWeight: 500,
    color: '#374151',
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
    transition: 'all 0.15s',
    whiteSpace: 'nowrap' as const,
  },
  emptyState: {
    gridColumn: '1 / -1',
    textAlign: 'center' as const,
    padding: '60px 0',
    color: '#94A3B8',
    fontSize: 14,
  },
  loadingState: {
    textAlign: 'center' as const,
    padding: '60px 0',
    color: '#94A3B8',
    fontSize: 14,
  },

  // Modal
  overlay: {
    position: 'fixed' as const,
    inset: 0,
    background: 'rgba(15,23,42,0.4)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    padding: 20,
  },
  modal: {
    background: '#FFFFFF',
    borderRadius: 16,
    padding: '28px',
    width: '100%',
    maxWidth: 420,
    boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: 600,
    color: '#0F172A',
    marginBottom: 4,
  },
  modalSubtitle: {
    fontSize: 13,
    color: '#94A3B8',
    marginBottom: 24,
  },
  modalLabel: {
    fontSize: 13,
    fontWeight: 500,
    color: '#374151',
    marginBottom: 8,
    display: 'block',
  },
  modalSelect: {
    width: '100%',
    height: 42,
    padding: '0 12px',
    borderRadius: 10,
    border: '1.5px solid #E2E8F0',
    background: '#F8FAFC',
    fontSize: 13,
    color: '#0F172A',
    fontFamily: "'DM Sans', sans-serif",
    outline: 'none',
    marginBottom: 24,
  },
  modalActions: {
    display: 'flex',
    gap: 10,
    justifyContent: 'flex-end',
  },
  cancelBtn: {
    height: 40,
    padding: '0 18px',
    borderRadius: 10,
    border: '1.5px solid #E2E8F0',
    background: '#FFFFFF',
    fontSize: 13,
    fontWeight: 500,
    color: '#374151',
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
  },
  confirmBtn: {
    height: 40,
    padding: '0 18px',
    borderRadius: 10,
    border: 'none',
    background: '#0F172A',
    fontSize: 13,
    fontWeight: 600,
    color: '#FFFFFF',
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
  },
}