import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  root: {
    padding: '32px 36px',
    fontFamily: "'DM Sans', sans-serif",
    maxWidth: 1400,
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 24,
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: 600,
    color: '#0F172A',
    letterSpacing: '-0.5px',
  },
  pageSubtitle: {
    fontSize: 13,
    color: '#94A3B8',
    marginTop: 4,
  },
  filtersRow: {
    display: 'flex',
    gap: 12,
    alignItems: 'center',
    flexWrap: 'wrap' as const,
  },
  select: {
    height: 40,
    padding: '0 12px',
    borderRadius: 10,
    border: '1.5px solid #E2E8F0',
    background: '#FFFFFF',
    fontSize: 13,
    color: '#0F172A',
    fontFamily: "'DM Sans', sans-serif",
    outline: 'none',
    cursor: 'pointer',
    minWidth: 160,
  },
  tableCard: {
    background: '#FFFFFF',
    border: '1px solid #E2E8F0',
    borderRadius: 16,
    overflow: 'hidden',
  },
  tableWrap: {
    overflowX: 'auto' as const,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
  },
  th: {
    fontSize: 11,
    fontWeight: 600,
    color: '#94A3B8',
    textAlign: 'left' as const,
    padding: '14px 16px',
    letterSpacing: '0.05em',
    textTransform: 'uppercase' as const,
    borderBottom: '1px solid #F1F5F9',
    background: '#FAFAFA',
  },
  td: {
    padding: '14px 16px',
    borderBottom: '1px solid #F8FAFC',
    verticalAlign: 'middle' as const,
  },
  reportId: {
    fontSize: 12,
    fontWeight: 600,
    color: '#94A3B8',
    fontFamily: 'monospace',
  },
  reportTitle: {
    fontSize: 13,
    color: '#0F172A',
    fontWeight: 500,
    display: 'block',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    maxWidth: 260,
  },
  reportDesc: {
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 2,
    display: 'block',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    maxWidth: 260,
  },
  categoryPill: {
    fontSize: 12,
    color: '#6366F1',
    background: '#EEF2FF',
    padding: '3px 10px',
    borderRadius: 20,
    display: 'inline-block',
  },
  dateText: {
    fontSize: 12,
    color: '#94A3B8',
  },
  actionBtn: {
    height: 32,
    padding: '0 14px',
    borderRadius: 8,
    border: '1.5px solid #E2E8F0',
    background: '#FFFFFF',
    fontSize: 12,
    fontWeight: 500,
    color: '#374151',
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  pagination: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    padding: '16px 20px',
    borderTop: '1px solid #F1F5F9',
  },
  pageBtn: {
    height: 36,
    padding: '0 16px',
    borderRadius: 8,
    border: '1.5px solid #E2E8F0',
    background: '#FFFFFF',
    fontSize: 13,
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
    color: '#374151',
    fontWeight: 500,
  },
  pageInfo: {
    fontSize: 13,
    color: '#94A3B8',
    padding: '0 8px',
  },
  emptyState: {
    textAlign: 'center' as const,
    padding: '60px 0',
    color: '#94A3B8',
    fontSize: 14,
  },
  loadingState: {
    textAlign: 'center' as const,
    padding: '60px 0',
    color: '#94A3B8',
    fontSize: 14,
  },

  // Modal
  overlay: {
    position: 'fixed' as const,
    inset: 0,
    background: 'rgba(15,23,42,0.4)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    padding: 20,
  },
  modal: {
    background: '#FFFFFF',
    borderRadius: 16,
    padding: '28px 28px',
    width: '100%',
    maxWidth: 440,
    boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: 600,
    color: '#0F172A',
    marginBottom: 4,
  },
  modalSubtitle: {
    fontSize: 13,
    color: '#94A3B8',
    marginBottom: 24,
  },
  modalLabel: {
    fontSize: 13,
    fontWeight: 500,
    color: '#374151',
    marginBottom: 8,
    display: 'block',
  },
  modalSelect: {
    width: '100%',
    height: 42,
    padding: '0 12px',
    borderRadius: 10,
    border: '1.5px solid #E2E8F0',
    background: '#F8FAFC',
    fontSize: 13,
    color: '#0F172A',
    fontFamily: "'DM Sans', sans-serif",
    outline: 'none',
    marginBottom: 16,
  },
  modalTextarea: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: 10,
    border: '1.5px solid #E2E8F0',
    background: '#F8FAFC',
    fontSize: 13,
    color: '#0F172A',
    fontFamily: "'DM Sans', sans-serif",
    outline: 'none',
    resize: 'vertical' as const,
    minHeight: 80,
    marginBottom: 24,
  },
  modalActions: {
    display: 'flex',
    gap: 10,
    justifyContent: 'flex-end',
  },
  cancelBtn: {
    height: 40,
    padding: '0 18px',
    borderRadius: 10,
    border: '1.5px solid #E2E8F0',
    background: '#FFFFFF',
    fontSize: 13,
    fontWeight: 500,
    color: '#374151',
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
  },
  confirmBtn: {
    height: 40,
    padding: '0 18px',
    borderRadius: 10,
    border: 'none',
    background: '#0F172A',
    fontSize: 13,
    fontWeight: 600,
    color: '#FFFFFF',
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
  },
}