import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  root: {
    padding: '32px 36px',
    fontFamily: "'DM Sans', sans-serif",
    maxWidth: 1100,
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 24,
  },
  backBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 13,
    fontWeight: 500,
    color: '#64748B',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontFamily: "'DM Sans', sans-serif",
    padding: 0,
    marginBottom: 4,
  },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
  },
  titleGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  pageTitle: {
    fontSize: 22,
    fontWeight: 600,
    color: '#0F172A',
    letterSpacing: '-0.5px',
  },
  metaRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap' as const,
  },
  metaItem: {
    fontSize: 13,
    color: '#64748B',
    display: 'flex',
    alignItems: 'center',
    gap: 4,
  },
  updateBtn: {
    height: 42,
    padding: '0 20px',
    borderRadius: 10,
    border: 'none',
    background: '#0F172A',
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: '1fr 340px',
    gap: 20,
    alignItems: 'start',
  },
  leftCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
  },
  rightCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
  },
  card: {
    background: '#FFFFFF',
    border: '1px solid #E2E8F0',
    borderRadius: 16,
    padding: '20px 24px',
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: '#0F172A',
    marginBottom: 16,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  descText: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 1.7,
  },
  mapWrap: {
    height: 280,
    borderRadius: 10,
    overflow: 'hidden',
    border: '1px solid #E2E8F0',
  },
  imageGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(120px, 1fr))',
    gap: 10,
  },
  imageThumb: {
    width: '100%',
    aspectRatio: '1',
    objectFit: 'cover' as const,
    borderRadius: 10,
    border: '1px solid #E2E8F0',
    cursor: 'pointer',
  },
  infoRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px 0',
    borderBottom: '1px solid #F8FAFC',
  },
  infoLabel: {
    fontSize: 12,
    color: '#94A3B8',
    fontWeight: 500,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  infoValue: {
    fontSize: 13,
    color: '#0F172A',
    fontWeight: 500,
  },
  historyList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
  },
  historyItem: {
    display: 'flex',
    gap: 12,
    paddingBottom: 20,
    position: 'relative' as const,
  },
  historyDot: {
    width: 10,
    height: 10,
    borderRadius: '50%',
    background: '#38BDF8',
    flexShrink: 0,
    marginTop: 4,
    position: 'relative' as const,
    zIndex: 1,
  },
  historyLine: {
    position: 'absolute' as const,
    left: 4,
    top: 14,
    bottom: 0,
    width: 2,
    background: '#F1F5F9',
  },
  historyContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    flex: 1,
  },
  historyStatus: {
    fontSize: 13,
    fontWeight: 600,
    color: '#0F172A',
  },
  historyNote: {
    fontSize: 12,
    color: '#64748B',
    lineHeight: 1.5,
  },
  historyDate: {
    fontSize: 11,
    color: '#94A3B8',
  },
  emptyHistory: {
    fontSize: 13,
    color: '#94A3B8',
    textAlign: 'center' as const,
    padding: '20px 0',
  },
  loadingWrap: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '60vh',
    color: '#94A3B8',
    fontSize: 14,
    fontFamily: "'DM Sans', sans-serif",
  },

  // Modal
  overlay: {
    position: 'fixed' as const,
    inset: 0,
    background: 'rgba(15,23,42,0.4)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    padding: 20,
  },
  modal: {
    background: '#FFFFFF',
    borderRadius: 16,
    padding: '28px 28px',
    width: '100%',
    maxWidth: 440,
    boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: 600,
    color: '#0F172A',
    marginBottom: 4,
  },
  modalSubtitle: {
    fontSize: 13,
    color: '#94A3B8',
    marginBottom: 24,
  },
  modalLabel: {
    fontSize: 13,
    fontWeight: 500,
    color: '#374151',
    marginBottom: 8,
    display: 'block',
  },
  modalSelect: {
    width: '100%',
    height: 42,
    padding: '0 12px',
    borderRadius: 10,
    border: '1.5px solid #E2E8F0',
    background: '#F8FAFC',
    fontSize: 13,
    color: '#0F172A',
    fontFamily: "'DM Sans', sans-serif",
    outline: 'none',
    marginBottom: 16,
  },
  modalTextarea: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: 10,
    border: '1.5px solid #E2E8F0',
    background: '#F8FAFC',
    fontSize: 13,
    color: '#0F172A',
    fontFamily: "'DM Sans', sans-serif",
    outline: 'none',
    resize: 'vertical' as const,
    minHeight: 80,
    marginBottom: 24,
  },
  modalActions: {
    display: 'flex',
    gap: 10,
    justifyContent: 'flex-end',
  },
  cancelBtn: {
    height: 40,
    padding: '0 18px',
    borderRadius: 10,
    border: '1.5px solid #E2E8F0',
    background: '#FFFFFF',
    fontSize: 13,
    fontWeight: 500,
    color: '#374151',
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
  },
  confirmBtn: {
    height: 40,
    padding: '0 18px',
    borderRadius: 10,
    border: 'none',
    background: '#0F172A',
    fontSize: 13,
    fontWeight: 600,
    color: '#FFFFFF',
    fontFamily: "'DM Sans', sans-serif",
    cursor: 'pointer',
  },
}